### PR TITLE
Rename @knora/ui to @dasch-swiss/dsp-ui and kui to dsp

### PR DESCRIPTION
**Pull request by kilchenmann**
https://dasch.myjetbrains.com/youtrack/issue/DSP-221

@flavens @mdelez You can test the changes with the integrated app or you can use my playground-app from here: https://github.com/kilchenmann/playground and add the @dasch-swiss/dsp-ui package with yalc.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
> I think there is a remnant of the renaming process that can be safely removed. (projects/knora-ui/src/lib/viewer/operations)

I think this is because git controls files, not folders. So maybe this is just a leftover on your local file system.

**Comment by mdelez** [comment]
> > I think there is a remnant of the renaming process that can be safely removed. (projects/knora-ui/src/lib/viewer/operations)
> 
> I think this is because git controls files, not folders. So maybe this is just a leftover on your local file system.

Huh, I think you're right. If I look at the file structure on github, I don't see the empty folder. I think it's good to approve then right?

**Comment by tobiasschweizer** [comment]
Just remove the empty folder from your file system and you are good :-)

**Comment by kilchenmann** [comment]
Thanks for approving 👍🏼 I will resolve the conflicts (because of previous PR) and merge afterwards

**Comment by kilchenmann** [comment]
@flavens @mdelez @tobiasschweizer @SepidehAlassi When this PR is merged, you have to be careful with your open PRs. There could be conflicts. But it doesn't make much sense to wait longer?!

**Pull request merged**
