### PR TITLE
Describe concept of value components

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-235

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@mdelez More English teaching ...

**Comment by mdelez** [comment]
@tobiasschweizer is it cool if I just checkout the branch and change things?

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer is it cool if I just checkout the branch and change things?

Fire at will ;-)

**Comment by tobiasschweizer** [comment]
> good to go :)

thanks a lot!

**Pull request merged**
