### PR TITLE
Make the sorting service more flexible

### PR DESCRIPTION
**Pull request by tobiasschweizer**
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-415

### CODE REVIEW

**Comment by flavens** [comment]
@tobiasschweizer I will review your PR with my PR

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer I will review your PR with my PR

Sorry, I don't know what that means.

**Comment by tobiasschweizer** [comment]
@flavens I added your use case  with `ReadProject[]` to the specs. Do you have also other use cases I should check for?

**Comment by flavens** [comment]
> @flavens I added your use case with `ReadProject[]` to the specs. Do you have also other use cases I should check for?

I have no other cases for now

**Pull request merged**
