### PR TITLE
List Value Component

### LINKED ISSUE #15: Viewer Value Component: ListValueComponent
Implement `BaseValueComponent` for a `ListValue`.

### PR DESCRIPTION
**Pull request by SepidehAlassi**
To display the value:

- [x] display list node labels as nested menus

To edit the value:

- [x] edit list value as a List node 

- [x] display the nodes of the root node in a nested drop-down menu

- [x] get the list node selected by the user and assign it to the object of list node property

- [x] edit comment value

- [x] cancel edit

test:

- [x] test display

- [x] test edit

- [x] test sublist component

closes #15

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@tobiasschweizer I just noticed that this PR has problems with the creation of list value. So please do not review it for now.

I vaguely remember that all list nodes of a project were supposed to share a root node, is that correct? I could not find anything in that regard in knora documentation.

I know that from the lists endpoint of [api-js-lib](https://github.com/dasch-swiss/knora-api-js-lib/blob/master/src/api/v2/list/lists-endpoint.ts) one can get a list with its root node IRI. 
Now, to create a list value, I need to first find this IRI. That would require a gravsearch for a listnode with (isRootNode == true). 

My question is, should I proceed with such a gravsearch or is there a function in api-js-lib that I miss which can already return the root node?

**Comment by tobiasschweizer** [comment]
> @tobiasschweizer I just noticed that this PR has problems with the creation of list value. So please do not review it for now.
> 
> I vaguely remember that all list nodes of a project were supposed to share a root node, is that correct? I could not find anything in that regard in knora documentation.
> 
> I know that from the lists endpoint of [api-js-lib](https://github.com/dasch-swiss/knora-api-js-lib/blob/master/src/api/v2/list/lists-endpoint.ts) one can get a list with its root node IRI.
> Now, to create a list value, I need to first find this IRI. That would require a gravsearch for a listnode with (isRootNode == true).
> 
> My question is, should I proceed with such a gravsearch or is there a function in api-js-lib that I miss which can already return the root node?

I think much like in the case of link values, you should find the info in the ontology:

> http://0.0.0.0:3333/ontology/0001/anything/v2#hasListItem: ResourcePropertyDefinition
id: "http://0.0.0.0:3333/ontology/0001/anything/v2#hasListItem"
subPropertyOf: ["http://api.knora.org/ontology/knora-api/v2#hasValue"]
comment: undefined
label: "Listenelement"
guiElement: "http://api.knora.org/ontology/salsah-gui/v2#List"
subjectType: "http://0.0.0.0:3333/ontology/0001/anything/v2#Thing"
objectType: "http://api.knora.org/ontology/knora-api/v2#ListValue"
isLinkProperty: false
isLinkValueProperty: false
isEditable: true
guiAttributes: ["hlist=<http://rdfh.ch/lists/0001/treeList>"]

`guiAttributes` contain the Iri of the root node, so you can the whole list with knora-api-js-lib: v2.list.getList https://dasch-swiss.github.io/knora-api-js-lib/classes/_api_v2_list_lists_endpoint_.listsendpoint.html#getlist

**Comment by tobiasschweizer** [comment]
I might wanna add a cache for whole lists (currently there is just a cache for list nodes). Actually this should be combined but it is kind of tricky ...

**Comment by SepidehAlassi** [comment]
@tobiasschweizer I believe this PR is ready to be reviewed.

**Comment by SepidehAlassi** [comment]
@flavens thank you for reviewing this PR Flavie.

**Comment by SepidehAlassi** [comment]
@flavens I've applied your suggestions.

**Pull request merged**
